# Generated by Django 3.2.7 on 2021-10-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('made', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
