# Generated by Django 3.2.7 on 2021-10-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework2polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=50)),
                ('train', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
